apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-pvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-kubernetes-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kubernetes-pvc
  template:
    metadata:
      labels:
        app: hello-kubernetes-pvc
    spec:
      containers:
      - name: hello-kubernetes-pvc
        image: paulbouwer/hello-kubernetes:1.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /var/lib/app/content
          name: content
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: content
        persistentVolumeClaim:
          claimName: app-content
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-content
spec:
  storageClassName: vc01cl01-t0compute
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
